### ISSUE TITLE
DSP

### ISSUE THREAD

**Issue by gladiator02** [gladiator02/ZSWI#1]

**Comment by moucek** [comment]
Přečetl jsem doc verzi dokumentace, vypadá dobře, nějaké minors: 
1.4.2. oblasti: vynechal bych kybernetiku a geomatiku a dal bych tam zeměpis, biologie, ostatní technické předměty 
3.6 místo Zobrazení výsledné vizualizace bych napsal vizualizace výsledků, taktéž podobně v dalších textech
3.3. při počítání shody klíčových termínů (preference uchazeče) a oboru počítat s vahami reprezentujícími výběr na škále preferencí jednotlivým klíčových termínů  - např. ne -0, spše ne - 0,25, nevadí - 0,5, spíše ano - 0,75, ano - 1,0 s tím, že tyto váhy budou nastavitelné jako parametry v administračním rozhraní  
- dále při výpočtu shody počítat příslušnost klíčového termínu k danému oboru
3.11 nechal bych administrátora vybrat i ze seznamu již existujících klíčových termínů, neb může použít stejný termín pro svůj obor (zavedený v jiném oboru) s jinou prioritou
 
přidání vah ke škále pro vyhodnocování klíčových slov - např. ne -0, spše ne - 0,25, navadí - 0,5, spíše ano - 0,75, ano - 1,0 s tím, že by je bylo možné a

**Comment by moucek** [comment]
Takto je ten předešlý komentář správně:
Přečetl jsem doc verzi dokumentace, vypadá dobře, nějaké minors:
1.4.2. oblasti: vynechal bych kybernetiku a geomatiku (asi neznají ze střední školy), místo nich zeměpis, biologie, ostatní technické předměty
3.6 místo Zobrazení výsledné vizualizace bych napsal Vizualizace výsledků, taktéž podobně v dalších textech
3.3. při počítání shody klíčových termínů (preference uchazeče) a oboru počítat s vahami reprezentujícími výběr na škále preferencí jednotlivých klíčových termínů - např. ne -0, spíše ne - 0,25, nevadí - 0,5, spíše ano - 0,75, ano - 1,0 s tím, že tyto váhy budou nastavitelné jako parametry v administračním rozhraní;
dále při výpočtu shody počítat příslušnost klíčového termínu k danému oboru 3.11 nechal bych administrátora vybrat i ze seznamu již existujících klíčových termínů, neb může použít stejný termín pro svůj obor (zavedený v jiném oboru) s jinou prioritou

**Comment by gladiator02** [comment]
Můžu teda zítra přinést k podepsání to prohlášení nebo to budete ještě někomu dávat k přečtení?

**Comment by moucek** [comment]
Dobrý den,

 

Poslal jsem to na děkanát ke komentování, mohou se ještě přihodit nějaké změny. Podpis můžeme ve vašem případě vyřešit na cvičení. RM.

**Comment by gladiator02** [comment]
Kybernetiku u Bc. nevím jak jinak nazvat nebo do jaké oblasti ji dát.

Bakalářské studium: 
Fyzika	Matematika	Informatika	Počítačová grafika	Biologie
Chemie	Ekonomika	Mechanika	Výpočetní technika	Stavitelství
Jazyky	Kybernetika	Zeměpis		Elektrotechnika

Navazující studium
Fyzika	Matematika	Informatika	Počítačová grafika	Stavitelství
Jazyky	Ekonomika	Mechanika	Geomatika	Kybernetika

Doktorské studium
Mechanika	Kybernetika	Fyzika	Matematika	Informatika
Geomatika	Výpočetní technika
