### ISSUE TITLE
Základní připomínky ke specifikaci

### ISSUE THREAD

**Issue by moucek** [gladiator02/ZSWI#12]
Specifikace je velmi strohá, určitě přidejte (kromě jiného): kontext - proč to děláme,vizualizaci - obrázky: jak bude uchazeč vybírat klíčová slova, jak bude vypadat zobrazení korelace jeho zájmu s existujícími obory, opravdu to bude fungovat na všech prohlížečích běžících na XP?, zkuste i navrhnout, jak bude vypadat administrátorská část + kouknout, kde bude na mojefavka link

**Comment by gladiator02** [comment]
Něco jsem tam dopsala
