### ISSUE TITLE
Graf - vizualizace

### ISSUE THREAD

**Issue by moucek** [gladiator02/ZSWI#43]
Na výsledném grafu jsou v některých případech těžko rozpoznatelné obory (aniž by je bylo nutné rozkliknout), neb jsou jejich jména zkracována - prosím o test jiných zobrazení, kde by se jména oborů objevovala celá

**Comment by gladiator02** [comment]
Když je jméno zkrácené, tak se nad popiskem zobrazuje tooltip s celým jménem.
Zvýšila jsem hranici pro zobrazení oboru v grafu na "průměr/3".
